---
# tasks file for user_pam_time
#- name: Inclide vars
#  include_vars: "{{ ansible_os_family }}.yml"

## Подключаем файл для конфигурирования pam модуля sshd
- name: Import install tasks pam_modules
  import_tasks: configure_pam_d_ssh.yml

## Подключаем файл конфигурации скрипт auth
- name: Import configure file for pam_modules pam_acc.sh
  import_tasks: configure_pam_script.yml

## Добавление пользователя
- name: add user user1
  import_tasks: add_users.yml

## Подключаем файл конфигурации скрипт auth
- name: Import configure file add group server
  import_tasks: configure-add-group.yml

## Установка пакета pam_script
- name: install pkg pam_script
  import_tasks: configure-host.yml
