---
# Создание пользователей и баз в Postgresql
- name: import create-user-db-zabbix.yml
  import_tasks: create-user-db-zabbix.yml
  tags: zabbix

- name: import create-user-db-barman.yml
  import_tasks: create-user-db-barman.yml
  tags: barman

- name: import create-user-db-odoo.yml
  import_tasks: create-user-db-odoo.yml
  tags: odoo

- name: import create-user-replication.yml
  import_tasks: create-user-replication.yml
  tags: replica

# - name: import configure-all-conf-to-postgresql.yml
#   import_tasks: configure-all-conf-to-postgresql.yml
#   tags: config

# - name: import reload-config-postgresql.yml
#   import_tasks: reload-config-postgresql.yml
#   tags: reload

# - name: import restart-cluster-postgresql.yml
#   import_tasks: restart-cluster-postgresql.yml
#   tags: restart