# Применение конфига после изменения
- name: restart postgresql cluster
  command:
    cmd: pg_ctlcluster 13 main restart

# - name: Select query to db acme with positional arguments and non-default credentials
#   postgresql_query:
#     db: acme
#     login_user: django
#     login_password: mysecretpass
#     query: SELECT * FROM acme WHERE id = %s AND story = %s
#     positional_args:
#     - 1
#     - test