- name: add password user barman
  user:
    name: barman
    password: '$6$Mg9iAn8Ski/1h7ER$JA24vpr21UcriXFesc20ugr.tJyhxFRtK8TxtMKftvAYeFRO69mVucGxauP7i6VTialg.eN6jZoLDz9Kkc1QV/'
    update_password: always