- name: apt install dep
  apt:
    name: gnupg2
    update_cache: yes

## Установка епозитория
- name: install repo list
  copy:
    src: pgdg.list
    dest: /etc/apt/sources.list.d/

## Установка ключа репозитория
- apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

## Устанавливаем Barman
- name: install barman
  apt:
    name: 
      - barman
      - rsync
      - postgresql-client-13
      - mc
    state: latest
    update_cache: yes

## Копируем скрипт восстановления из бекапа в barman
- name: copy script backup_restore_latest.sh
  copy:
    src: backup_restore_latest.sh
    dest: /var/lib/barman/
    owner: "barman"
    group: "barman"
    mode: '0644'

