## Установка zabbix-agent
- name: install zabbix-agent
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when:
    ansible_os_family == "Debian"

- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
    update_cache: yes
  when:
    ansible_os_family == "RedHat"