---
## Конфигурим sshd_config
- name: configure sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

## Конфигурим ssh_config
- name: configure sshd_config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
  notify:
    - ssh restart