# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
:inetRouter01 => {
    :box_name => "centos/7",
    :vm_name => "inetRouter",
    #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                {ip: '10.10.20.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "srv-net"},
                {ip: '10.10.30.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "web-net"},
                {ip: '192.168.56.254', adapter: 8},
                ]
            },
    :webserver01 => {
        :box_name => "centos/7",
        :vm_name => "webserver-01",
        :net => [
                {ip: '10.10.20.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "srv-net"},
                {ip: '10.10.30.10', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "web-net"},
                {ip: '10.10.40.10', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "db-net"},
                # {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                # {ip: '192.168.255.9', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
                # {ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
                {ip: '192.168.56.200', adapter: 8},
                ]
            },
    # :webserver02 => {
    #     :box_name => "centos/7",
    #     :vm_name => "webserver-02",
    #     :net => [
    #         {ip: '10.10.20.11', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "router-net"},
    #         # {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
    #         # {adapter: 3, auto_config: false, virtualbox__intnet: true},
    #         # {adapter: 4, auto_config: false, virtualbox__intnet: true},
    #         {ip: '192.168.56.201', adapter: 8},
    #             ]
    #         },

    :basedb01 => {
        :box_name => "debian11/v1230.1",
        :vm_name => "basedb-01",
        :net => [
            {ip: '10.10.20.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "srv-net"},
            {ip: '10.10.40.20', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "db-net"},
            {ip: '192.168.41.20', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "dbr-net"},
            # {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "managers-net"},
            # {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192",   virtualbox__intnet: "office1-net"},
            {ip: '192.168.56.20', adapter: 8},
                ]
            },

    :basedb02 => {
        :box_name => "debian11/v1230.1",
        :vm_name => "basedb-02",
        :net => [
            {ip: '10.10.20.21', adapter: 2, netmask: "255.255.255.0",virtualbox__intnet: "srv-net"},
            {ip: '10.10.40.21', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "db-net"},
            {ip: '192.168.41.21', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "dbr-net"},
            {ip: '192.168.56.21', adapter: 8},
                ]
            },

    :logserver => {
        :box_name => "centos/7",
        :vm_name => "logserver",
        :net => [
            {ip: '10.10.20.30', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "srv-net"},
            # {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
            # {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
            # {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net"},
            {ip: '192.168.56.30', adapter: 8},
                ]
            },

    :backup => {
        :box_name => "centos/7",
        :vm_name => "backup",
        :net => [
            {ip: '10.10.20.31', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "srv-net"},
            {ip: '192.168.56.31', adapter: 8},
                ]
            },
}

Vagrant.configure("2") do |config|MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
    end
        if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
    end 
        box.vm.provision "shell", inline: <<-SHELL
        cat /vagrant/provision/vagrant-key.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
#         case boxname.to_s
#         when "inetRouter"
#         box.vm.provision "shell", run: "always", inline: <<-SHELL
# sysctl net.ipv4.conf.all.forwarding=1
# iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j
# MASQUERADE
# SHELL
# when "centralRouter"
# box.vm.provision "shell", run: "always", inline: <<-SHELL
# sysctl net.ipv4.conf.all.forwarding=1
# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
# echo "GATEWAY=192.168.255.1" >>
# /etc/sysconfig/network-scripts/ifcfg-eth1
# systemctl restart network
# SHELL
# when "centralServer"
# box.vm.provision "shell", run: "always", inline: <<-SHELL
# echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
# echo "GATEWAY=192.168.0.1" >>
# /etc/sysconfig/network-scripts/ifcfg-eth1
# systemctl restart network
# SHELL
# end
        end
    end
end