# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    ns01.vm.hostname = "ns01"
    ns01.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync_auto: "true",
    rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
    client.vm.hostname = "client"
    client.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync_auto: "true",
    rsync_exclude: [".git/",".vagrant/",".gitignore","Vagrantfile"]
  end

end
