- name: apt install gnupg2 nginx mc
  apt:
    name: 
      - gnupg2
      - mc
    update_cache: yes

## Установка епозитория
- name: install repo odoo.list
  copy:
    src: odoo.list
    dest: /etc/apt/sources.list.d/
  
## Установка ключа репозитория
- apt_key:
    url: "https://nightly.odoo.com/odoo.key"
    state: present

# Установка сервера odoo
- name: Install odoo
  apt:
    name: odoo
    state: latest
    update_cache: yes

# Установка конфигурации odoo для подключения к postgresql
- name: configure odoo.conf for postgresql
  template:
    src: odoo.conf.j2
    dest: /etc/odoo/odoo.conf
  notify:
    - restart odoo