## Создаем файл конфигурации
- name: Create file clientserv.conf
  file:
    path: /etc/openvpn/client/clientserv.conf
    owner: "root"
    group: "root"
    mode: '0644'
    state: touch
  when: 
      - ansible_hostname == "vpnclient"

## Конфигурируем openvpn-client
- name: copy file clientserv.conf to openvpn-client
  template:
    src: clientserv.conf.j2
    dest: /etc/openvpn/client/clientserv.conf
  #notify:
  #  - restart openvpn_client
  when: 
      - ansible_hostname == "vpnclient"

## Разрешаем пересылку пакетов между интерфейсами
- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
  when:
    - ansible_hostname == "vpnclient"

   ## Создать каталог /var/log/openvpn
- name: Create folder /var/log/openvpn
  file:
    path: /var/log/openvpn
    state: directory
    owner: root
    group: root
    mode: 0664
  when: 
    - ansible_hostname == "vpnclient" 

## Запускаем openvpn-client
- name: Enable a timer unit for dnf-automatic
  systemd:
    name: openvpn-client@clientserv
    state: started
    enabled: yes
  when:
    - ansible_hostname == "vpnclient"