## Install epel-release
- name: Install epel-relese
  yum:
    name: epel-release
  when:
    ansible_distribution == "CentOS"

# Install ovpn
- name: install ovpn server
  yum:
    name:
      - openvpn
      - easy-rsa
      - mc
      - tcpdump
      - net-tools
    state: latest
  when: ansible_hostname == "vpnserver"
  
  # Install ovpn client
- name: install ovpn client
  yum:
    name:
      - openvpn
      - mc
      - tcpdump
      - net-tools
    state: latest
  when: ansible_hostname == "vpnclient"