## Устанваливаем параметры конфига, используя шаблон j2
- name: reconfigure zabbix_server.conf
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: 
    - restart zabbix-server
    - restart apache2