---
# handlers file for postgres-create-slave
## Перезапуск службы postgresql
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted

- name: restart postgresql cluster
  command:
    cmd: pg_ctlcluster 13 main restart
